davidmyersdev/octo

public/CNAME
src/router.js

- closes #2 
The landing page is just a blank page right now, so just redirect it.

Redirect landing page to new document page

---

src/App.vue

- resolves #12 
- resolves #23 
The editor autosaves, so we really just need to prevent the default browser behavior on `cmd+s`.

Add cmd+s shortcut

---

src/components/DocumentList.vue
src/components/TheEditor.vue
src/store/modules/documents.js
src/store/plugins/caching/documents.js

Instead of excluding encrypted documents that cannot be decrypted (from a missing or incorrect key), we will instead load them as normal and just exclude them from the current UI. Eventually, I would love to introduce a "vault" list to allow users to see that they have encrypted documents (like if they haven't supplied keys yet on a new client) and even decrypt documents with alternative keys.

Load and filter out documents that cannot be decrypted

---

src/components/Exporter.vue
src/components/TheSettings.vue
src/router.js

- resolves #42 
In the settings menu, there is now an "Export Documents" button. This will convert all documents to JSON and decrypt them if possible. The JSON will then be available to copy/paste from the editor. Eventually, this should automatically prompt for a download, but this is a good first step.

Add basic export feature to settings menu

---

src/common/parsers.js

Fixes #48 
Previously, tags with a `-` character would discard the dash and
anything afterwards. For example `#my-tag` would become `#my`.
The reason for this is the regex `\w` does not include `-`. Update the
regex to include `-` explicitly allows the use of `-` to create
"dasherized" tags.

Add support for tags with dashes

---

src/components/CommandK.vue
src/components/ModK.vue
src/components/ModKKey.vue
src/components/TheSidebar.vue
src/main.js
src/store.js
src/store/actions.js

Resolves #20 
On mac, the modifier key is `cmd` while other systems will most likely use
`ctrl`. The underlying keybinding plugin handles this situation already
but Octo did not adjust the visual hints in the UI for non mac users.
To solve this, we look for `Macintosh` in the user agent. If present,
display `cmd` as the mod key in keybinding hints. Otherwise, we assume
`ctrl`.
This is calculated when initializing the app. We set this state in the
store.

Detect and display mod key based on user agent

---

package-lock.json
src/common/codemirror_helper.js
src/components/MarkdownEditor.vue

This upgrades CodeMirror to add WebAssembly text format (wast) support for code blocks. This also changes the CDN URL to match the package version.

Upgrade CodeMirror (for wast support) and use package version for CDN

---

src/App.vue

Resolves #52 
Currently, the windows version of this scrollbar isn't super consistent
with the theme of octo. Inversely, the OSX version is a bit hard to see
IMO.
To solve this we create a custom scrollbar across OSX/Windows with definitions to support Firefox, Chrome, Edge, etc.
Super open to feedback on the actual design. Threw this together and thought it looked alright on multiple browsers/OS but not tied to any particular setting.

Customize scrollbar for cross OS consistency

---

src/App.vue
src/components/Context.vue
src/components/DiscardableAction.vue
src/components/DocumentList.vue
src/components/Exporter.vue
src/components/TagList.vue
src/components/TheContent.vue
src/components/TheEditor.vue
src/components/TheSidebar.vue
src/components/icons/Info.vue
src/components/labels/Info.vue
src/store.js
src/store/actions.js

- closes #65 
This moves the existing actions into a new "meta" panel that can be toggled from the editor view. The new meta panel also shows tags in the active document and the document's relevant timestamps.

Add Document meta panel

---

src/App.vue
src/common/codemirror_helper.js
src/components/MarkdownEditor.vue
src/components/TheEditor.vue
src/components/TheSettings.vue
src/store.js
src/store/modules/settings.js
src/store/plugins/caching/settings.js

Resolves #60 
Take advantage of the CodeMirror keyMap property to support a VIM mode when desired. There's still some improvements to styling that could be made but I think the bones are all there. This approach also makes it easy to add additional modes for emacs and sublime.
One downside is were always pulling in the https://codemirror.net/keymap/vim.js file. We could come up with a solution to lazy load it.

Support a vim editor mode

---

src/components/TheSettings.vue
src/store/plugins/caching/settings.js

This was accidentally removed in an amendment commit in #61.

Persist keyMap setting

---

src/components/MarkdownEditor.vue

- closes #68 
Use the default text color for lists (same as normal text). Use an accent color for the list tokens (`-`, `1.`, etc).

Use neutral colors for lists and list accents

---

src/components/MarkdownEditor.vue

Vim was not being loaded until after a page refresh when the config was changed from "Default" to "Vim" in the Settings component.

Fix for same-session Vim config change

---

src/App.vue
src/components/DiscardableAction.vue
src/components/TheContent.vue
src/components/TheEditor.vue
src/components/TheSidebar.vue

- closes #76 
Mobile content overflow behavior is now fixed (regression introduced by previous changes). Menu items have been titleized.

Fix mobile content overflow

---

src/App.vue
src/common/code_sandbox.js
src/common/markdown/markdown.js
src/common/markdown/utils.js
src/common/parsers.js
src/components/MarkdownEditor.vue
src/components/MarkdownEditorImage.vue
src/components/TheSettings.vue
src/store/modules/settings.js
src/store/plugins/caching/settings.js

- closes #79 
CodeMirror line widgets allow us to inject elements either above or below lines in the editor. Using this feature, we can scan the document for image tags (ignoring code) and build the elements to inject into the document. This feature has two corresponding settings: Images Enabled (to toggle the entire feature) and Show Captions (to toggle just the captions).

Render images from markdown image tags

---

public/index.html
src/App.vue
src/views/Dashboard.vue

- closes #87 
Scrolling was completely broken on iOS (and in Safari on desktop). This was apparently due to a number of conflating factors including the `overflow-hidden` class at the top level in `App.vue`, the use of `h-100`, and `d-flex`. This caused the content to be clipped and therefore not scrollable. The solution was to migrate to using flex (`d-flex`, `flex-column`, `flex-grow-1`, `flex-shrink-1`) to manage containers of vertical content.
Note: All browsers on iOS use Safari web views, so this was likely broken in all browsers on iOS.

Fix scrolling in Safari (and other iOS browsers)

---

src/components/Graph.vue

This embeds the document list on the graph page. It shows all documents for the selected tag when selecting a node.

Show relevant docs when selecting a graph node

---

src/components/Graph.vue

- closes #101 
This is necessary on desktop where windows are often resized and repositioned.

101: Automatically resize the graph on window size changes

---

public/index.html

- closes #121
The `html` container was not using flex, so the body tag was not being resized when the keyboard drawer was closed (related to `fill-available`).

Use flex on html tag to adjust height dynamically

---

README.md
src/App.vue
src/components/Editor.vue
src/components/TheRightSidebar.vue
src/router.js
src/views/Editor.vue
yarn.lock

This fixes a bug where viewing a shared doc would create a local copy with the same id and redirect to it.

Bugfix: Stop persisting shared docs

---

CHANGELOG.md
CONTRIBUTING.md
src/components/Editor.vue
src/components/TheContent.vue
src/store/modules/keybindings.js
src/views/Editor.vue
src/views/Example.vue

Speech-to-text was not working, because creating a new doc caused the Editor view to refresh. The refresh was previously handled by retrieving/supplying the selection at the time of redirect, but that solution did not work for mobile speech-to-text. Instead, we will prevent the Editor view from refreshing when a doc is created.

Bugfix: Speech-to-text does not work correctly

---

src/vendor/plugins/references/completions.ts
src/vendor/plugins/references/index.ts
test/e2e/editor.spec.ts

Show multiple direct link suggestions in a single line

---

.github/workflows/ci.yml
app.vue
assets/css/tailwind.css
components/CoreEditor.vue
components/CoreEditorToolbar.vue
components/CoreInput.vue
components/CoreLink.vue
components/FlexDivider.vue
components/Gutter.vue
composables/useToggle.ts
composables/useZen.ts
layouts/dashboard.vue
nuxt.config.ts
package.json
pages/menu.vue
playwright.config.ts
pnpm-lock.yaml
tailwind.config.cjs
test/cypress/e2e/sharing.cy.ts
test/e2e/editor.spec.ts
test/e2e/healthchecks/index.spec.ts

Refresh the UI for the dashboard layout
