src/components/Editor.vue

closes #1 
Using an implicit fixed position for now. There might be a better way, but this should work for the time being.

Fix position of discard button on scroll

---

public/welcome.md
src/main.js

Add a welcome note on first time use. This note will include some basic usages instructions.

Add welcome note

---

src/App.vue
src/components/NoteList.vue
src/router.js
src/views/Dashboard.vue

Add document search feature. Allow filtering by regex or plain text with optional case sensitivity.

Add search feature

---

src/App.vue
src/views/Dashboard.vue

Fix UI inconsistencies

---

src/components/TheSidebar.vue

- closes #45 
As the title says

Add padding to bottom of tag list to clear browser URL preview

---

src/components/MarkdownEditor.vue

Added #9e9e9e as custom color for code block comments.
This fixes #35 Change code block comment color

Added custom color for code block comment

---

src/components/TheNavbar.vue
src/store/modules/settings.js

- closes #78 
Existing settings stored in IndexedDB are overriding the defaults. This change will perform a deep merge to ensure defaults are respected when overrides are not specified for existing users.

Fix settings error caused by Vim mode implementation

---

src/components/Extendable.vue
src/components/TheSettings.vue
src/components/settings/Editor.vue
src/components/settings/Encryption.vue
src/components/settings/Export.vue
src/main.js
src/packages/interface.js
src/packages/manager.js
src/packages/test/Hello.vue
src/packages/test/index.js
src/store/plugins/packages.js

- relates to #91 
I just want to get a loose idea started to build on. This is far from ready, but I think some of the concepts - like the `Extendable` component or the `PackageManager` class - are a step in the right direction.

Implement basic package system

---

package-lock.json
package.json
src/App.vue
src/components/Graph.vue
src/components/Importer.vue
src/components/TheLeftSidebar.vue
src/router.js

This PR adds a new Tag visualizer to help show the relationships between all document tags. Eventually, this will also include functionality to interact with the graph to explore documents.

Add Tag Visualizer

---

src/App.vue
src/components/Graph.vue

- Improve network graph on light mode (and use theme color for nodes)
- Use a dark text color on default buttons

Theme improvements

---

src/components/TheEditor.vue

- closes #104 
This PR fixes the current undo bug.

104: Prevent undo from clearing the entire document (on document load)

---

src/components/DocumentList.vue
src/components/TheEditor.vue
src/components/TheLeftSidebar.vue
src/components/TheNavbar.vue
src/components/TheRightSidebar.vue
src/main.js
src/models/doc.js
src/router.js
src/store/modules/documents.js
src/store/modules/keybindings.js
src/views/Daily.vue

- closes #95 
This adds a new Daily Notepad page which returns a specific, distinct document every day. This page will always return the current daily doc or create a new one if it does not exist. The cutoff time is 3:00 AM (client time) to account for night-owls (like myself). After 3:00 AM, visiting the page will create a new document for that day.

95: Add Daily Notepad feature

---

lib/vue-ink/README.md
lib/vue-ink/src/Ink.vue
package.json
src/App.vue
src/components/settings/Editor.vue
src/router.js
src/store/modules/settings.js
src/store/plugins/caching/settings.js
src/views/Editor.vue
yarn.lock

This PR adds the ability to opt-in to the new [Ink](https://github.com/writewithocto/ink) editor.

Integrate the new Ink editor behind a setting

---

src/components/Context.vue
src/components/TheLeftSidebar.vue
src/components/TheNavbar.vue
src/store.js
src/store/modules/contexts.js
src/store/plugins/caching/contexts.js

Allow users to store named contexts.

118: Ability to save contexts

---

src/components/Context.vue
src/components/TheLeftSidebar.vue
src/store/modules/contexts.js

Sort contexts alphabetically

---

package.json
public/example.md
src/components/Editor.vue
src/components/settings/Editor.vue
src/main.js
src/router.js
src/views/Editor.vue
src/views/Example.vue
src/views/Home.vue
tailwind.config.js
vite.config.ts
yarn.lock

Add landing page

---

src/App.vue
src/components/settings/Theme.vue
src/store/modules/settings.js
src/views/Editor.vue
src/views/Example.vue

Made some changes for an auto theme. Changes in this PR are from Editor, App, Example, Theme vue files and settings.js

180: Add option to automatically match the system theme

---

package.json
src/App.vue
src/components/Editor.vue
src/components/settings/Editor.vue
src/components/settings/Theme.vue
src/data/changelog.json
src/store/modules/settings.js
src/store/plugins/caching/settings.js
src/views/Editor.vue
tailwind.config.js
vite.config.ts
yarn.lock

- Add support for the new Formatting Toolbar from [Ink](https://github.com/writewithocto/ink)
- Allow users to configure the Editor content max-width by number of characters
- Upgrade Tailwind to v3 (and update other dependencies)
- Apply some small fixes for the new 'auto' theme

Add the new Formatting Toolbar (and more)

---

src/components/Editor.vue
src/models/doc.js
src/views/Editor.vue
src/views/Example.vue
src/views/FileEditor.vue

Make plugins reactive

---

index.html
src/components/TheLeftSidebar.vue
src/firebase.js
src/global.ts
src/main.ts
src/router.js
src/views/Home.vue
vite.config.ts

This PR makes a few changes so that Octo can run even when there are no Firebase values provided.

Allow the app to run without Firebase

---

vercel.json

Update Vercel config

---

layouts/editor.vue
pages/docs/[doc].vue
pages/docs/[doc]/meta.vue
src/router.js

- closes #213
A few routes were missed during the recent route updates (preparing for Nuxt).

Bugfix: Fix public docs

---

components/Editor.vue
package.json
pnpm-lock.yaml
src/vendor/plugins/mermaid/index.ts
src/vendor/plugins/mermaid/language.ts
src/vendor/plugins/mermaid/theme.ts
src/vendor/plugins/mermaid/widget.ts

- Add [`codemirror-lang-mermaid`](https://github.com/inspirnathan/codemirror-lang-mermaid) to support syntax highlighting for some Mermaid languages.
- Debounce chart updates to prevent jumpiness caused by full decoration rebuilds on doc changes.

Feature: Add `codemirror-lang-mermaid`

---

components/Assistant.vue
components/AssistantEditor.vue
components/ChatMessage.vue
components/CoreAssetDismiss.vue
components/CoreEditor.vue
components/CoreMenuItem.vue
components/Editor.vue
components/Toast.vue
components/ToastList.vue
composables/injectOr.ts
composables/injectOrProvide.ts
composables/useRoot.ts
composables/useToasts.ts
layouts/dashboard.vue
package.json
pnpm-lock.yaml
src/vendor/plugins/mermaid/widget.ts
src/vendor/plugins/readonly/index.ts
src/vendor/plugins/references/replacements.ts
tailwind.config.cjs

Add support for system instructions

Add support for system instructions

---

.github/workflows/ci.yml
env.d.ts
nuxt.config.ts
package.json
pnpm-lock.yaml
test/cypress/cypress.d.ts
test/cypress/e2e/encryption.cy.ts
test/cypress/support/commands.ts
test/cypress/tsconfig.json
test/unit/composables/injectOr.test.ts
test/unit/composables/injectOrProvide.test.ts
test/utils/index.ts
tsconfig.json
vite.config.ts

- Add `vitest` and a few basic unit tests
- Improve CI performance with caching and job orchestration

Add `vitest`

---

.github/workflows/ci.yml
.github/workflows/deploy.yml
.github/workflows/preview.yml
manifest.ts
nuxt.config.ts
package.json
pnpm-lock.yaml
pwa.config.ts
vite.config.ts

- Prevent 500 errors on new deploys
- Ensure the app still works offline

Improve the PWA build

---

composables/useAuth.ts
composables/useLayout.ts
composables/useRoot.ts
layouts/minimal.vue
package.json
pages/authenticate.vue

Disable sign-in page when logged in

---

components/Assistant.vue
components/CoreAsset.vue
components/CoreAssetDismiss.vue
components/CoreAssetFeedback.vue
components/CoreAssetGitHub.vue
components/CoreAssetLogo.vue
components/CoreAssetTwitter.vue
components/Tag.vue
composables/useAssistant.ts
layouts/minimal.vue
pages/menu.vue

- Allow the user to select the chat model used in Assistant

Make Assistant model configurable

---

.eslintignore
.github/workflows/healthchecks.yml
.gitignore
.vscode/settings.json
package.json
playwright.config.ts
pnpm-lock.yaml
test/e2e/healthchecks/index.spec.ts

Add Playwright for production healthchecks and end-to-end tests

Add Playwright

---

components/CoreNavPanel.vue
components/DocLink.vue
composables/usePinnedDocs.ts
layouts/dashboard.vue
pages/docs/[docId]/index.vue
pages/docs/[docId]/meta.vue
pages/menu.vue
src/common/parsers.ts
src/models/doc.ts
test/e2e/editor.spec.ts

Display backlinks on the active doc.

Add backlinks

---

components/CoreEditor.vue
components/CoreInput.vue
layouts/dashboard.vue

Clean up the UI a bit more

---

components/Assistant.vue
components/CoreFormControlGroup.vue
components/CoreFormControlLayout.vue
components/CoreListboxButton.vue
components/CoreListboxOptions.vue
components/CoreMenu.vue
composables/useSystemInstructions.ts
helpers/database.ts
pages/assistant/system-instructions/new.vue

Make it possible to save system instructions

---

assets/css/tailwind.css
components/Assistant.vue
components/AssistantChatMessage.vue
components/CoreSwitch.vue
components/Key.vue
package.json
pages/dev/design-system/themes/index.vue
pnpm-lock.yaml

Add support for Vision in GPT-4 Turbo and GPT-4o

---

.eslintrc-rules.json
.vscode/settings.json
app.vue
assets/css/tailwind.css
components/Assistant.vue
components/AssistantEditor.vue
components/CoreEditor.vue
components/CoreListboxButton.vue
components/CorePage.vue
components/CoreScrollable.vue
components/Doc.vue
components/DocList.vue
components/Gutter.vue
components/Modal.vue
composables/useMarkdown.ts
composables/useSearch.ts
error.vue
package.json
pages/assistant/system-instructions/new.vue
pages/docs/[docId]/meta.vue
pages/force-graph.vue
pages/menu.vue
pnpm-lock.yaml
src/store/plugins/caching/documents.js
src/utils/dom.ts
src/utils/markdown.ts
tsconfig.json

Improve search
